<?xml version="1.0" encoding="UTF-8"?>
<!-- March 8, 2007 -->
<wsdl:definitions
   name="parlayx_payment_reserve_amount_charging_service"
   targetNamespace="http://www.csapi.org/wsdl/parlayx/payment/reserve_amount_charging/v3_1/service"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:tns="http://www.csapi.org/wsdl/parlayx/payment/reserve_amount_charging/v3_1/service"
   xmlns:interface="http://www.csapi.org/wsdl/parlayx/payment/reserve_amount_charging/v3_1/interface">

   <wsdl:import namespace="http://www.csapi.org/wsdl/parlayx/payment/reserve_amount_charging/v3_1/interface" location="parlayx_payment_reserve_amount_charging_interface_3_1.wsdl"/>

   <wsdl:binding name="ReserveAmountChargingBinding" type="interface:ReserveAmountCharging">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="reserveAmount">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>

      <wsdl:operation name="reserveAdditionalAmount">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>

      <wsdl:operation name="chargeReservation">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>

      <wsdl:operation name="releaseReservation">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="ReserveAmountChargingService">
      <wsdl:port name="ReserveAmountCharging" binding="tns:ReserveAmountChargingBinding">
         <soap:address location="http://localhost:9080/ReserveAmountChargingService/services/ReserveAmountCharging"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
