<?xml version="1.0" encoding="UTF-8"?>
<!-- May 25, 2007 -->
<wsdl:definitions
   name="parlayx_sms_notification_manager_service"
   targetNamespace="http://www.csapi.org/wsdl/parlayx/sms/notification_manager/v3_2/service"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:tns="http://www.csapi.org/wsdl/parlayx/sms/notification_manager/v3_2/service"
   xmlns:interface="http://www.csapi.org/wsdl/parlayx/sms/notification_manager/v3_2/interface">

   <wsdl:import namespace="http://www.csapi.org/wsdl/parlayx/sms/notification_manager/v3_2/interface" location="parlayx_sms_notification_manager_interface_3_2.wsdl"/>

   <wsdl:binding name="SmsNotificationManagerBinding" type="interface:SmsNotificationManager">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="startSmsNotification">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>

      <wsdl:operation name="stopSmsNotification">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>

      <wsdl:operation name="startDeliveryReceiptNotification">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>

      <wsdl:operation name="stopDeliveryReceiptNotification">
         <soap:operation soapAction="" style="document"/>
            <wsdl:input>
               <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
               <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
               <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
            <wsdl:fault name="PolicyException">
               <soap:fault name="PolicyException" use="literal"/>
            </wsdl:fault>
      </wsdl:operation>
   </wsdl:binding>

   <wsdl:service name="SmsNotificationManagerService">
      <wsdl:port name="SmsNotificationManager" binding="tns:SmsNotificationManagerBinding">
         <soap:address location="http://localhost:9080/SmsNotificationManagerService/services/SmsNotificationManager"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>
