<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.csapi.org/wsdl/parlayx/data/sync/v1_0/service" xmlns:interface="http://www.csapi.org/wsdl/parlayx/data/sync/v1_0/interface" name="sag_data_sync_service" targetNamespace="http://www.csapi.org/wsdl/parlayx/data/sync/v1_0/service">
	<wsdl:import namespace="http://www.csapi.org/wsdl/parlayx/data/sync/v1_0/interface" location="sag_data_sync_interface_1_0.wsdl"/>
	<wsdl:binding name="DataSyncBinding" type="interface:DataSync">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="syncSubscriptionData">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="changeMSISDN">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="syncOrderRelation">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="syncMSISDNChange">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="syncSubscriptionActive">
			<soap:operation soapAction="" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="DataSyncService">
		<wsdl:port name="DataSync" binding="tns:DataSyncBinding">
			<soap:address location="http://localhost:9080/DataSyncService/services/DataSync"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
